name: GitHub Actions accessibility demo
on: [push]
jobs:
  accesibility-automation:
    name: Accesibility
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install axe
        run: npm install @axe-core/cli -g
      - name: run axe
        run: axe https://www.bioconductor.org/
