name: KPI automation
on:
  push:
    branches:
      - redesign2023
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
      - "fix/**"
      - "feat/**"
  workflow_run:
    workflows:
      - Pr - Preview
      - Deploy To staging
    types:
      - completed
jobs:
  kpi_metrics:
    permissions:
      pull-requests: write
    name: All KPI metrics
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: find-url
        run: |
          if [ ${{github.ref_name }} == redesign2023 ]; then
                echo "URL_TO_USE=${{vars.STAGING_URL}}" >> "$GITHUB_ENV"
          else
                echo "URL_TO_USE=http://pr-preview-bioconductor-pr${{github.event.number}}.s3-website-us-east-1.amazonaws.com" >> "$GITHUB_ENV"
          fi
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
      - name: install psi and axe
        run: |
          npm install psi
          npm install @axe-core/cli -g
      - name: run desktop psi
        run: |
          echo "DESKTOP_PSI_RESULTS<<EOF" >> $GITHUB_ENV
          echo "$(node psi.js ${{env.URL_TO_USE}} desktop 50)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: run mobile psi
        run: |
          echo "MOBILE_PSI_RESULTS<<EOF" >> $GITHUB_ENV
          echo "$(node psi.js ${{env.URL_TO_USE}} mobile 50)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: add_comment_pageSpeed
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ${{env.DESKTOP_PSI_RESULTS}}
            ${{env.MOBILE_PSI_RESULTS}}
          message-id: psi
      - name: run axe accesibility test
        run: |
          echo "AXE_RESULTS<<EOF" >> $GITHUB_ENV
          echo "$(axe ${{env.URL_TO_USE}})" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: add_comment_axe
        uses: mshick/add-pr-comment@v2
        with:
          message: ${{env.AXE_RESULTS}}
          message-id: axe
      - name: send notification psi
        if: ${{ github.ref == 'refs/heads/redesign2023' }}
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          text: "${{env.DESKTOP_PSI_RESULTS}} \n ${{env.MOBILE_PSI_RESULTS}}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK}}
      - name: send notification axe
        if: ${{ github.ref == 'refs/heads/redesign2023' }}
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          text: "${{env.AXE_RESULTS}}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK}}
