name: KPI automation
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
      - "fix/**"
      - "feat/**"
    branches-ignore:
      - redesign2023
  workflow_run:
    workflows:
      - Pr - Preview
      - Deploy To staging
    types:
      - completed

jobs:
  pagespeed-automation:
    name: Performance from pagespeed
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: find-url
        run: |
          if [ ${{github.ref_name }} == redesign2023 ]; then
                echo "URL=${{secrets.STAGING_URL}}" >> "$GITHUB_ENV"
          else
                echo "URL=http://pr-preview-bioconductor-pr${{github.event.number}}.s3-website-us-east-1.amazonaws.com"
          fi
      - name: PageSpeed Insights - Desktop
        uses: jakepartusch/psi-action@v1.3
        with:
          url: ${{ env.URL }}
          strategy: desktop
      - name: PageSpeed Insights - Mobile
        uses: jakepartusch/psi-action@v1.3
        with:
          url: ${{ env.URL }}
          strategy: mobile
      - name: install node for axe
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install axe
        run: npm install @axe-core/cli -g
      - name: run axe accesibility test
        run: axe  ${{ env.URL }}
