name: PageSpeed Automation
on:
  pull_request:
jobs:
  kpi_metrics:
    name: All KPI metrics
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
      - name: install psi and axe
        run: |
          npm install psi
          npm install @axe-core/cli -g
      - name: run desktop psi
        run: |
          echo "DESKTOP_PSI_RESULTS<<EOF" >> $GITHUB_ENV
          echo "$(node psi.js https://www.bioconductor.org/ desktop 50)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: run mobile psi
        run: |
          echo "MOBILE_PSI_RESULTS<<EOF" >> $GITHUB_ENV
          echo "$(node psi.js https://www.bioconductor.org/ mobile 50)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
  slack-notifications:
    name: notify slack
    runs-on: ubuntu-latest
    needs: kpi_metrics
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: send notification
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          text: "${{env.DESKTOP_PSI_RESULTS}} \n ${{env.MOBILE_PSI_RESULTS}}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK}} # required
        if: always()
