name: PageSpeed Automation
on: push
jobs:
  run-pagespeed-desktop:
    name: pagespeed metrics for desktop
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
      - name: install psi
        run: npm install psi
      - name: Mobile
        run: DESKTOP_PSI_RESULTS=$(echo node psi.js https://www.bioconductor.org/ desktop 50)
      - name: add_comment
        run: |
          echo $DESKTOP_PSI_RESULTS
