name: PageSpeed Automation
on: [push]
jobs:
  run-pagespeed-performance:
    name: Performance Metrics for desktop
    runs-on: ubuntu-latest
    steps:
      - name: PageSpeed Insights - Desktop
        id: abc
        uses: jakepartusch/psi-action@v1.3
        with:
          url: "https://www.bioconductor.org/"
          strategy: desktop
      - name: results
        id: results
        run: echo "${{toJSON(steps.abc.outputs)}}"

  run-pagespeed-performance-mobile:
    name: Performance Metrics for mobile
    runs-on: ubuntu-latest
    steps:
      - name: running Pagespeed
        uses: jakepartusch/psi-action@v1.3
        with:
          url: "https://www.bioconductor.org/"
          strategy: mobile
