name: PageSpeed Automation
on: [push]
jobs:
  run-pagespeed-performance:
    name: Performance Metrics for desktop
    runs-on: ubuntu-latest
    steps:
      - name: PageSpeed Insights - Desktop
        id: abc
        uses: jakepartusch/psi-action@v1.3
        with:
          url: "https://www.bioconductor.org/"
          strategy: desktop
      - name: print outputs
        run: echo "${{steps.abc.outputs}}"
      - name: Store Workflow Logs
        uses: actions/github-script@v4
        id: store_logs
        with:
          script: |
            const logs = require('fs').readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8');
            console.log(logs);
            return {
              logs: logs
            }
      - name: Display Stored Logs
        run: echo "${{ steps.store_logs.outputs.logs }}"
  run-pagespeed-performance-mobile:
    name: Performance Metrics for mobile
    runs-on: ubuntu-latest
    steps:
      - name: running Pagespeed
        uses: jakepartusch/psi-action@v1.3
        with:
          url: "https://www.bioconductor.org/"
          strategy: mobile
      - name: Store Workflow Logs
        uses: actions/github-script@v4
        id: store_logs
        with:
          script: |
            const logs = require('fs').readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8');
            console.log(logs);
            return {
              logs: logs
            }
      - name: Display Stored Logs
        run: echo "${{ steps.store_logs.outputs.logs }}"
