name: PageSpeed Automation
on:
  pull_request:
jobs:
  kpi_metrics:
    name: All KPI metrics
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
      - name: install psi and axe
        run: |
          npm install psi
          npm install @axe-core/cli -g
      - name: run desktop psi
        run: |
          echo "DESKTOP_PSI_RESULTS<<EOF" >> $GITHUB_ENV
          echo "$(node psi.js https://www.bioconductor.org/ desktop 50)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: run mobile psi
        run: |
          echo "MOBILE_PSI_RESULTS<<EOF" >> $GITHUB_ENV
          echo "$(node psi.js https://www.bioconductor.org/ mobile 50)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
  slackNotification-psi-Desktop:
    needs: kpi_metrics
    name: Slack Notification
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/redesign2023'
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Desktop KPIs
          SLACK_MESSAGE: ${{env.DESKTOP_PSI_RESULTS}}
  slackNotification-psi-Mobile:
    needs: kpi_metrics
    name: Slack Notification
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/redesign2023'
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Desktop KPIs
          SLACK_MESSAGE: ${{env.MOBILE_PSI_RESULTS}}
