name: PageSpeed Automation
on: [push]
jobs:
  run-pagespeed-desktop:
    name: Performance Metrics for desktop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
      - name: install psi
        run: npm install psi
      - name: Desktop
        id: desktop
        run: |
          echo "DESKTOP_RESULTS<<EOF" >> $GITHUB_ENV
          echo "$(node psi.js https://www.bioconductor.org/ desktop 70)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: add_comment
        run: echo "${{ env.DESKTOP_RESULTS }}""
  run-pagespeed-performance-mobile:
    name: Performance Metrics for mobile
    runs-on: ubuntu-latest
    steps:
      - name: running Pagespeed
        uses: jakepartusch/psi-action@v1.3
        with:
          url: "https://www.bioconductor.org/"
          strategy: mobile
