name: PageSpeed Automation
on:
  pull_request:
jobs:
  kpi_metrics:
    name: All KPI metrics
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
      - name: install psi and axe
        run: |
          npm install psi
          npm install @axe-core/cli
      - name: run desktop psi
        run: $DESKTOP_PSI_RESULTS << $(node psi.js ${{env.URL_TO_USE}} desktop 50)
      - name: do console
        run: echo "$DESKTOP_PSI_RESULTS"
