name: PageSpeed Automation
on: push
jobs:
  run-pagespeed-desktop:
    name: pagespeed metrics for desktop
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
      - name: install psi
        run: npm install psi
      - name: Mobile
        run: |
          echo "MOBILE_RESULTS<<EOF" >> $GITHUB_ENV
          echo "$(node psi.js https://www.bioconductor.org/ desktop 70)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: add_comment
        run: |
          echo "${{env.MOBILE_RESULTS}}"
