name: PageSpeed Automation
on: [push]
jobs:
  run-pagespeed-performance:
    name: Performance Metrics for desktop
    runs-on: ubuntu-latest
    steps:
      - name: PageSpeed Insights - Desktop
        uses: jakepartusch/psi-action@v1.3
        with:
          url: "https://www.bioconductor.org/"
          threshold: 95
          strategy: desktop
  run-pagespeed-performance-mobile:
    name: Performance Metrics for mobile
    runs-on: ubuntu-latest
    steps:
      - name: running Pagespeed
        uses: jakepartusch/psi-action@v1.3
        with:
          url: "https://www.bioconductor.org/"
          threshold: 95
          strategy: mobile
