name: PageSpeed Automation
on:
  pull_request:
jobs:
  kpi_metrics:
    name: All KPI metrics
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
      - name: install psi and axe
        run: npm install @axe-core/cli -g
      - name: run axe accesibility test
        run: |
          echo "AXE_RESULTS<<EOF" >> $GITHUB_ENV
          echo "$(axe ${{env.URL_TO_USE}})" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: send notification axe
        if: ${{ github.ref == 'refs/heads/redesign2023' }}
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          text: "${{env.AXE_RESULTS}}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK}}
