name: PageSpeed Automation
on: [push]
jobs:
  run-pagespeed-performance:
    name: Performance Metrics for desktop
    runs-on: ubuntu-latest
    steps:
      - name: Run PageSpeed Insights - Desktop
        id: desktop-psi
        run: |
          output=$(bash -c "jakepartusch/psi-action@v1.3 --url=${{ env.URL_TO_USE }} --strategy=desktop" 2>&1)
          echo "::set-output name=psi-output::$output"
      - name: results
        id: results
        run: echo "${{toJSON(steps.abc.outputs)}}"

  run-pagespeed-performance-mobile:
    name: Performance Metrics for mobile
    runs-on: ubuntu-latest
    steps:
      - name: running Pagespeed
        uses: jakepartusch/psi-action@v1.3
        with:
          url: "https://www.bioconductor.org/"
          strategy: mobile
